Add sleep to restart
IMIO/imio.updates pull request #2
Opened 2021-11-08 14:29 UTC by MagDhyIm

Can you merge my changes ? please =)

2021-11-08 14:53 UTC, odelaere commented
@MagDhyIm Can you make shure it dosn't wait after the last process of a buildout ?
Just checking the number of processes isn't enough ;)

2021-11-09 08:00 UTC, sgeulette requested changes, later dismissed
voir commentaires

2021-11-09 08:00 UTC, sgeulette commented on src/imio/updates/update_instances.py
> +                        response = requests.get('http://localhost:%s/%s/ok' % (bldt['port'], bldt['plone']))
bldt['port'] contient toujours la même valeur à savoir le port de l'instance1. 
On ne teste donc pas ici si le process en cours de redémarrage répond...
Cette façon de faire n'est pas bonne.
Il faudrait récupérer le process id du process en cours de redémarrage, pour trouver ensuite le port utilisé.

2021-11-09 08:00 UTC, sgeulette commented on src/imio/updates/update_instances.py
> +                run_spv(buildouts[bldt], 'restart', [p for p in buildouts[bldt]['spv'] if p.startswith('instance')], wait=True)
Il faudrait passer cette option wait en paramètre global du script.

2021-11-09 11:12 UTC, odelaere commented on src/imio/updates/update_instances.py
> +                        response = requests.get('http://localhost:%s/%s/ok' % (bldt['port'], bldt['plone']))
Je vais le chercher dans le port comme celui de l'instance1

2021-11-16 09:18 UTC, merged